<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Customers</name>
   <tag></tag>
   <elementGuidId>0a303f1f-4e2b-4df7-9da6-782e2d6706a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cust</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cust']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7abb7147-a8c6-4a85-8596-657a525dfc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>e0473d93-0035-4cfc-9026-125f186e0522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cust</value>
      <webElementGuid>6ed07ed0-ad00-4e9f-bb33-6f96e34d98d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>8fa9017f-acb2-483c-abdc-4fe2a5707d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#cust_sub</value>
      <webElementGuid>5ad9f914-4042-449f-8826-8cfd36e0c610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>96ab65ff-bb88-4302-a959-ba881bf6b4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Customers</value>
      <webElementGuid>a32048f8-80a8-4873-90c9-435e689dea85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cust&quot;)</value>
      <webElementGuid>68d133e4-fb65-4446-906a-bda28f5565eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cust']</value>
      <webElementGuid>2fbcd5df-eb0b-4e13-ad35-691996a60ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newSidenav']/nav/div/div/ul/li[6]/a</value>
      <webElementGuid>3573862e-d8e1-4601-b04c-22a876c0ac18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment History'])[1]/following::a[1]</value>
      <webElementGuid>25518bac-fc39-4fac-9943-b20c405d91a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk Transaction Log'])[1]/following::a[2]</value>
      <webElementGuid>ba970dfc-5af6-4786-a094-097978163716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Customers'])[1]/preceding::a[1]</value>
      <webElementGuid>71bf08b6-253b-4f47-83ae-0eeab3df28a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download CSV Template'])[1]/preceding::a[2]</value>
      <webElementGuid>b0d3439e-12e5-401f-a19f-51988ed89211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customers']/parent::*</value>
      <webElementGuid>bef41a33-1652-4865-a65d-f90cc5a97ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[3]</value>
      <webElementGuid>465a6c72-b0aa-49f6-b221-00e2e2228038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>a8206a89-f7da-4ece-bb2b-f0f6f27d431c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cust' and (text() = '
                            Customers' or . = '
                            Customers')]</value>
      <webElementGuid>5bcd5b96-e327-4080-9ea9-e8a6cbb76b8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
