<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Customers</name>
   <tag></tag>
   <elementGuidId>29663e0f-8e61-4c88-bc14-62fd8365a958</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cust_sub > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;redirect_overlay('https://stage.mobipaid.com/merchant/customer')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dc97d128-d101-4245-9614-2d05cd19ff9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>redirect_overlay('https://stage.mobipaid.com/merchant/customer')</value>
      <webElementGuid>c6389682-9a48-4cb0-9ddb-bede902a9048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Customers</value>
      <webElementGuid>58fe6ace-35a5-435d-ac26-c250c54dd47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cust_sub&quot;)/li[1]/a[1]</value>
      <webElementGuid>159f5f6f-833a-40ad-a69b-90fc7186618d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;redirect_overlay('https://stage.mobipaid.com/merchant/customer')&quot;]</value>
      <webElementGuid>029becb5-a5e0-4aa6-be40-ddaa8e67e15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cust_sub']/li/a</value>
      <webElementGuid>1c5f95b9-086c-4434-90bc-3e66b44658ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My Customers')]</value>
      <webElementGuid>b511bc8e-5abf-49db-a878-49b1c2272bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment History'])[1]/following::a[2]</value>
      <webElementGuid>3e52bfe8-bb29-401d-9a11-f83e93218959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download CSV Template'])[1]/preceding::a[1]</value>
      <webElementGuid>2406ef29-1efe-4140-a7a0-1f8068e74703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download XLS Template'])[1]/preceding::a[2]</value>
      <webElementGuid>47a9b630-516f-4d34-bed5-a40979b9081d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Customers']/parent::*</value>
      <webElementGuid>adbab405-01ee-4b93-9855-345f5449f3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li/a</value>
      <webElementGuid>40bd3d80-f039-4704-9873-177d03670d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'My Customers' or . = 'My Customers')]</value>
      <webElementGuid>01b2d2c3-3e7c-40db-a48d-9bdd04d0a83f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
