<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MERCHANT LOGIN_password</name>
   <tag></tag>
   <elementGuidId>68177118-e0ee-44af-b31e-c31465bab945</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#forPasswd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='forPasswd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7987a43-c687-45ae-afde-1d751422e083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>421e505d-e3d9-4424-ae9a-e1e26fd6559b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forPasswd</value>
      <webElementGuid>edafed71-a250-4043-9c6d-88b705b5e51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bd1fa23e-4947-4ba7-b389-5a34d6635160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password-border fixed-input login-placeholder</value>
      <webElementGuid>d815a30e-e27b-417c-bc4f-caf2d07a0d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>2be71054-3fb7-42fc-98bd-86972ef70f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0d627c17-240b-4642-b87d-a6cb7792f42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>22c90c5d-0a19-4316-986c-a6cc536f0ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forPasswd&quot;)</value>
      <webElementGuid>cb23dbb1-e6a3-480a-ab74-e3810f960b23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='forPasswd']</value>
      <webElementGuid>7cf522ad-69fc-4f9b-b589-018e77730371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[6]/input</value>
      <webElementGuid>27b7bad3-8c0d-4e85-8134-cc261a5b0674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>30a64c39-9629-419b-8830-202cf83af85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'forPasswd' and @name = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>4085a5a1-d055-4624-b407-2e40162820ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
