<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_email</name>
   <tag></tag>
   <elementGuidId>5bfebe7f-3d4e-4e53-b305-52804ec59946</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#thisEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='thisEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>555a1f22-f240-43a2-ab74-06d4dca8e4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b6908e3-ef85-4f67-a5fa-3d5597063455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>15e82484-5b0b-48fe-adf4-18ed20b4393b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>thisEmail</value>
      <webElementGuid>b74645a7-5bc0-4c58-bd81-f6ae87e7fec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>06c5e05b-6c09-48fd-b058-5027af93bd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>96443533-0a4e-465f-a5dd-5a27bd251e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addCustomers&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content mp-modalbox&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;main-modal-content&quot;]/div[@class=&quot;customer-field&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;cust-modalForm field-group&quot;]/input[@id=&quot;thisEmail&quot;]</value>
      <webElementGuid>90d3c18f-abb5-46d0-8851-4529238de3b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='thisEmail']</value>
      <webElementGuid>d514dd95-5024-4f02-87cf-ccb7a46cf8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addCustomers']/div/div/div/div[3]/div[3]/div[3]/div/div/input</value>
      <webElementGuid>7101574f-242f-4520-bfd3-6619fa249d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>703555f5-2945-413b-bdd5-613b8d00d689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email' and @id = 'thisEmail' and @placeholder = 'Email']</value>
      <webElementGuid>df674453-88da-4d82-ae3a-5549db4237a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
