<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_State  Province  Region_state_add</name>
   <tag></tag>
   <elementGuidId>22c2cf41-7f7a-4ba2-ba36-b3d90450394e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#state_add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='state_add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a201302-b31a-491a-bb08-50c0d96c48af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>state_add</value>
      <webElementGuid>933d01ff-6a27-4228-9aca-208061f7af4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>state_add</value>
      <webElementGuid>d844396c-0980-41f7-94d8-522cff0b014b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4902adb9-34ca-4885-a15f-727710bdcac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border-grey</value>
      <webElementGuid>63f494fb-0cfb-4da1-a19f-09c436c2d114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>State / Province / Region</value>
      <webElementGuid>94849ea1-9c69-4951-84fb-d3ca181c23bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;state_add&quot;)</value>
      <webElementGuid>a7af2c0c-a2b6-4712-86a4-58d11d6d0169</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='state_add']</value>
      <webElementGuid>b5a92469-43f7-4339-af73-6d8fbde0fcfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='state_input_wrapper_add']/input</value>
      <webElementGuid>ff123502-bb8a-480c-a2ba-1f6b9b79d410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/input</value>
      <webElementGuid>dce7f3a9-c652-4764-be59-23077c185a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'state_add' and @id = 'state_add' and @type = 'text' and @placeholder = 'State / Province / Region']</value>
      <webElementGuid>15f15f2e-245b-4750-a400-1e225d61e0a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
