<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address line 1_address_line1</name>
   <tag></tag>
   <elementGuidId>1a33945a-cc77-4ccc-9519-b93e3e2a490e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_line1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_line1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22e9a763-5e30-47c8-84bf-9c85495377cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5cbd9bf2-471f-4526-a23c-8caf40432141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address_line1</value>
      <webElementGuid>d6b6794c-3429-4ed9-bfcd-1197b5ef21ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_line1</value>
      <webElementGuid>57aa7983-4776-4792-ac35-3c164febca7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>513fefe6-6e63-427d-bb65-cec885c5c4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>Address line 1</value>
      <webElementGuid>7951501d-248c-42b3-8caf-7eee3083785e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address line 1</value>
      <webElementGuid>f21ead2a-4a84-4e6a-96f2-1b37439f6bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addCustomers&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content mp-modalbox&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;main-modal-content&quot;]/div[@class=&quot;customer-field&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10&quot;]/div[@class=&quot;cust-modalForm field-group&quot;]/input[@id=&quot;address_line1&quot;]</value>
      <webElementGuid>6c05d973-2167-46b1-a8b0-1239e305636f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_line1']</value>
      <webElementGuid>a58c333b-73d5-4c45-8bd2-7d35d51a98d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addCustomers']/div/div/div/div[3]/div[3]/div[4]/div/div/input</value>
      <webElementGuid>20f06fc2-8d50-4a5b-8a3b-3e4067f9fd19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>ae24be18-3b5b-485b-8af1-f7194d310d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address_line1' and @id = 'address_line1' and @placeholder = 'Address line 1']</value>
      <webElementGuid>407a41f0-b989-4ec7-b13c-05cb91cf4247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
