<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Indonesia</name>
   <tag></tag>
   <elementGuidId>4382b49a-e018-4035-8779-cc03e75cead2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iti-12__item-id > span.iti__country-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='iti-12__item-id']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8442651b-18a2-4e3f-a6c9-2f4a5e86910c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__country-name</value>
      <webElementGuid>c6c0d307-4812-4685-83b8-c722b4a89389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia</value>
      <webElementGuid>02a42184-eec6-4650-82db-de4d9b2806a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iti-12__item-id&quot;)/span[@class=&quot;iti__country-name&quot;]</value>
      <webElementGuid>02a5876a-47f2-411d-9886-58a8f75394dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='iti-12__item-id']/span</value>
      <webElementGuid>d78d64e9-af6a-402a-9a8f-17dfbf4a3dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India (भारत)'])[1]/following::span[2]</value>
      <webElementGuid>cec0d67d-49ce-4c04-95a7-a772b666ba95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iceland (Ísland)'])[1]/following::span[4]</value>
      <webElementGuid>2ff4672c-4434-485a-ab51-e2d371813331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iran (‫ایران‬‎)'])[1]/preceding::span[2]</value>
      <webElementGuid>5b4cda74-0bea-4bb5-81db-ef69f9314e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iraq (‫العراق‬‎)'])[1]/preceding::span[4]</value>
      <webElementGuid>db8c5ed2-b658-4ea2-99e4-c5203fb761ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Indonesia']/parent::*</value>
      <webElementGuid>ebe28dd6-7cee-4caa-b402-b714dc63320f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[103]/span</value>
      <webElementGuid>2f6f6a36-4cd4-4de1-8467-7a7dc930b2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Indonesia' or . = 'Indonesia')]</value>
      <webElementGuid>4f55c4d7-76bc-4543-b505-20ca76404816</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
