<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_state</name>
   <tag></tag>
   <elementGuidId>1512d768-0bc0-4f1f-ab6e-866a15aaf610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;state&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='state']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88958a95-6b36-4e41-91a0-5ed015cb5f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>state</value>
      <webElementGuid>8cda0988-1788-4ee1-bdf2-38cb2ef7fbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3744243c-06a4-43d4-aefc-1b8a4b0e7c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border-grey</value>
      <webElementGuid>44c14c52-b666-4733-ba5f-3d308fdfb2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input your state</value>
      <webElementGuid>5d9b0534-08c9-4d8f-902d-5c40b357d1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;state_input_wrapper&quot;)/input[@class=&quot;form-control border-grey&quot;]</value>
      <webElementGuid>b61e2be0-3800-4b43-8550-5ebe91a7af72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='state']</value>
      <webElementGuid>9103d54b-ba74-4b7b-bdf1-f52a774d0490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='state_input_wrapper']/input</value>
      <webElementGuid>f9f92138-f539-42e3-a633-94f3f9c98eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/input</value>
      <webElementGuid>3485aacb-f1f7-45ba-9086-b8acce8f6067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'state' and @type = 'text' and @placeholder = 'Input your state']</value>
      <webElementGuid>7b721357-a684-4c90-962a-d2b08c3187d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
