<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MERCHANT LOGIN_password</name>
   <tag></tag>
   <elementGuidId>6a6ef296-94bd-4524-892c-5d26fa8bc66f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#forPasswd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='forPasswd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e73f097-ba6d-405e-9c9a-c415bea746c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1cbabcd0-f0e5-4d1e-a1a3-ef96dbcd857e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forPasswd</value>
      <webElementGuid>69b6f371-6119-4083-8e0f-d2ae469980e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ffb842bb-4373-4d78-b4a0-1e678a837511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password-border fixed-input login-placeholder</value>
      <webElementGuid>be7dc0cf-df30-47c8-a248-2fbddf0269fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>43ebce09-53c7-4c2a-8f71-cc23cbce7444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9d79bac-bbe7-4be0-a7b1-ce1cfc0ff128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>942da9f8-bc91-4c0d-987e-fd384475c496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forPasswd&quot;)</value>
      <webElementGuid>fa37b1ff-a3e9-4a6c-aa20-84abdad2e5ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='forPasswd']</value>
      <webElementGuid>d215720f-35fd-46d0-acab-360d6ee62891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[6]/input</value>
      <webElementGuid>de4db12f-e9c1-4adf-98b8-ae8ec53f9717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>a661779a-c836-4dc4-8294-a4c24ee9801b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'forPasswd' and @name = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>10babc65-f304-4a62-9cf7-c093bc757f84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
